/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/international": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.international.id"];
          firstname?: parameters["rowFilter.international.firstname"];
          email?: parameters["rowFilter.international.email"];
          created_at?: parameters["rowFilter.international.created_at"];
          represented_by?: parameters["rowFilter.international.represented_by"];
          attending?: parameters["rowFilter.international.attending"];
          lastname?: parameters["rowFilter.international.lastname"];
          last_visited_at?: parameters["rowFilter.international.last_visited_at"];
          responded_at?: parameters["rowFilter.international.responded_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["international"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** international */
          international?: definitions["international"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.international.id"];
          firstname?: parameters["rowFilter.international.firstname"];
          email?: parameters["rowFilter.international.email"];
          created_at?: parameters["rowFilter.international.created_at"];
          represented_by?: parameters["rowFilter.international.represented_by"];
          attending?: parameters["rowFilter.international.attending"];
          lastname?: parameters["rowFilter.international.lastname"];
          last_visited_at?: parameters["rowFilter.international.last_visited_at"];
          responded_at?: parameters["rowFilter.international.responded_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.international.id"];
          firstname?: parameters["rowFilter.international.firstname"];
          email?: parameters["rowFilter.international.email"];
          created_at?: parameters["rowFilter.international.created_at"];
          represented_by?: parameters["rowFilter.international.represented_by"];
          attending?: parameters["rowFilter.international.attending"];
          lastname?: parameters["rowFilter.international.lastname"];
          last_visited_at?: parameters["rowFilter.international.last_visited_at"];
          responded_at?: parameters["rowFilter.international.responded_at"];
        };
        body: {
          /** international */
          international?: definitions["international"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/international_tokens": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.international_tokens.id"];
          firstname?: parameters["rowFilter.international_tokens.firstname"];
          email?: parameters["rowFilter.international_tokens.email"];
          created_at?: parameters["rowFilter.international_tokens.created_at"];
          represented_by?: parameters["rowFilter.international_tokens.represented_by"];
          attending?: parameters["rowFilter.international_tokens.attending"];
          lastname?: parameters["rowFilter.international_tokens.lastname"];
          last_visited_at?: parameters["rowFilter.international_tokens.last_visited_at"];
          responded_at?: parameters["rowFilter.international_tokens.responded_at"];
          token?: parameters["rowFilter.international_tokens.token"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["international_tokens"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** international_tokens */
          international_tokens?: definitions["international_tokens"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.international_tokens.id"];
          firstname?: parameters["rowFilter.international_tokens.firstname"];
          email?: parameters["rowFilter.international_tokens.email"];
          created_at?: parameters["rowFilter.international_tokens.created_at"];
          represented_by?: parameters["rowFilter.international_tokens.represented_by"];
          attending?: parameters["rowFilter.international_tokens.attending"];
          lastname?: parameters["rowFilter.international_tokens.lastname"];
          last_visited_at?: parameters["rowFilter.international_tokens.last_visited_at"];
          responded_at?: parameters["rowFilter.international_tokens.responded_at"];
          token?: parameters["rowFilter.international_tokens.token"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.international_tokens.id"];
          firstname?: parameters["rowFilter.international_tokens.firstname"];
          email?: parameters["rowFilter.international_tokens.email"];
          created_at?: parameters["rowFilter.international_tokens.created_at"];
          represented_by?: parameters["rowFilter.international_tokens.represented_by"];
          attending?: parameters["rowFilter.international_tokens.attending"];
          lastname?: parameters["rowFilter.international_tokens.lastname"];
          last_visited_at?: parameters["rowFilter.international_tokens.last_visited_at"];
          responded_at?: parameters["rowFilter.international_tokens.responded_at"];
          token?: parameters["rowFilter.international_tokens.token"];
        };
        body: {
          /** international_tokens */
          international_tokens?: definitions["international_tokens"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** @description International Invites */
  international: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: text */
    firstname: string;
    /** Format: text */
    email?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `international.id`.<fk table='international' column='id'/>
     */
    represented_by?: number;
    /** Format: boolean */
    attending?: boolean;
    /** Format: text */
    lastname: string;
    /** Format: timestamp with time zone */
    last_visited_at?: string;
    /** Format: timestamp with time zone */
    responded_at?: string;
  };
  international_tokens: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id?: number;
    /** Format: text */
    firstname?: string;
    /** Format: text */
    email?: string;
    /** Format: timestamp with time zone */
    created_at?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `international.id`.<fk table='international' column='id'/>
     */
    represented_by?: number;
    /** Format: boolean */
    attending?: boolean;
    /** Format: text */
    lastname?: string;
    /** Format: timestamp with time zone */
    last_visited_at?: string;
    /** Format: timestamp with time zone */
    responded_at?: string;
    /** Format: text */
    token?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description international */
  "body.international": definitions["international"];
  /** Format: bigint */
  "rowFilter.international.id": string;
  /** Format: text */
  "rowFilter.international.firstname": string;
  /** Format: text */
  "rowFilter.international.email": string;
  /** Format: timestamp with time zone */
  "rowFilter.international.created_at": string;
  /** Format: bigint */
  "rowFilter.international.represented_by": string;
  /** Format: boolean */
  "rowFilter.international.attending": string;
  /** Format: text */
  "rowFilter.international.lastname": string;
  /** Format: timestamp with time zone */
  "rowFilter.international.last_visited_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.international.responded_at": string;
  /** @description international_tokens */
  "body.international_tokens": definitions["international_tokens"];
  /** Format: bigint */
  "rowFilter.international_tokens.id": string;
  /** Format: text */
  "rowFilter.international_tokens.firstname": string;
  /** Format: text */
  "rowFilter.international_tokens.email": string;
  /** Format: timestamp with time zone */
  "rowFilter.international_tokens.created_at": string;
  /** Format: bigint */
  "rowFilter.international_tokens.represented_by": string;
  /** Format: boolean */
  "rowFilter.international_tokens.attending": string;
  /** Format: text */
  "rowFilter.international_tokens.lastname": string;
  /** Format: timestamp with time zone */
  "rowFilter.international_tokens.last_visited_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.international_tokens.responded_at": string;
  /** Format: text */
  "rowFilter.international_tokens.token": string;
}

export interface operations {}

export interface external {}
