/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/guests": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.guests.id"];
          firstname?: parameters["rowFilter.guests.firstname"];
          email?: parameters["rowFilter.guests.email"];
          created_at?: parameters["rowFilter.guests.created_at"];
          represented_by?: parameters["rowFilter.guests.represented_by"];
          attending?: parameters["rowFilter.guests.attending"];
          lastname?: parameters["rowFilter.guests.lastname"];
          last_visited_at?: parameters["rowFilter.guests.last_visited_at"];
          responded_at?: parameters["rowFilter.guests.responded_at"];
          pin?: parameters["rowFilter.guests.pin"];
          international?: parameters["rowFilter.guests.international"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["guests"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** guests */
          guests?: definitions["guests"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.guests.id"];
          firstname?: parameters["rowFilter.guests.firstname"];
          email?: parameters["rowFilter.guests.email"];
          created_at?: parameters["rowFilter.guests.created_at"];
          represented_by?: parameters["rowFilter.guests.represented_by"];
          attending?: parameters["rowFilter.guests.attending"];
          lastname?: parameters["rowFilter.guests.lastname"];
          last_visited_at?: parameters["rowFilter.guests.last_visited_at"];
          responded_at?: parameters["rowFilter.guests.responded_at"];
          pin?: parameters["rowFilter.guests.pin"];
          international?: parameters["rowFilter.guests.international"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.guests.id"];
          firstname?: parameters["rowFilter.guests.firstname"];
          email?: parameters["rowFilter.guests.email"];
          created_at?: parameters["rowFilter.guests.created_at"];
          represented_by?: parameters["rowFilter.guests.represented_by"];
          attending?: parameters["rowFilter.guests.attending"];
          lastname?: parameters["rowFilter.guests.lastname"];
          last_visited_at?: parameters["rowFilter.guests.last_visited_at"];
          responded_at?: parameters["rowFilter.guests.responded_at"];
          pin?: parameters["rowFilter.guests.pin"];
          international?: parameters["rowFilter.guests.international"];
        };
        body: {
          /** guests */
          guests?: definitions["guests"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  guests: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: text */
    firstname: string;
    /** Format: text */
    email?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `guests.id`.<fk table='guests' column='id'/>
     */
    represented_by?: number;
    /** Format: boolean */
    attending?: boolean;
    /** Format: text */
    lastname: string;
    /** Format: timestamp with time zone */
    last_visited_at?: string;
    /** Format: timestamp with time zone */
    responded_at?: string;
    /**
     * Format: text
     * @default substr((extensions.uuid_generate_v4())::text, 0, 7)
     */
    pin: string;
    /** Format: boolean */
    international: boolean;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description guests */
  "body.guests": definitions["guests"];
  /** Format: bigint */
  "rowFilter.guests.id": string;
  /** Format: text */
  "rowFilter.guests.firstname": string;
  /** Format: text */
  "rowFilter.guests.email": string;
  /** Format: timestamp with time zone */
  "rowFilter.guests.created_at": string;
  /** Format: bigint */
  "rowFilter.guests.represented_by": string;
  /** Format: boolean */
  "rowFilter.guests.attending": string;
  /** Format: text */
  "rowFilter.guests.lastname": string;
  /** Format: timestamp with time zone */
  "rowFilter.guests.last_visited_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.guests.responded_at": string;
  /** Format: text */
  "rowFilter.guests.pin": string;
  /** Format: boolean */
  "rowFilter.guests.international": string;
}

export interface operations {}

export interface external {}
